models/Notice.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Notice extends ActiveRecord
{
    public static function tableName() {
        return 'notice';
    }
}

controllers/NoticeController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Notice;
use yii\helpers\Url;
use yii\filters\AccessControl;

class NoticeController extends Controller {

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'add', 'edit', 'delete', 'post'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'denyCallback' => function($rule, $action) {
                    throw new \Exception('У вас нет доступа к этой странице');
                }
            ]
        ];
    }


    public function actionIndex()
    {
        // далаем сессию чтобы записывать уведомления которые уже были показаны
        $session = Yii::$app->session;
        $notNoticeId = $session->has('userNotice') ? $session->get('userNotice'): [];

        // берем одну новую запись, которую ещё не видел пользователеь
        $notice = Notice::find()->where(['not in','id', $notNoticeId])->one();
        if(!empty($notice->id) && !in_array($notice->id, $notNoticeId)) {
            array_push($notNoticeId, $notice->id);
            $session->set('userNotice', ($notNoticeId));

            // отметим что просмотрели уведомление
            $notice->countviews++;
            $notice->save();

            // показываем сообщение
            die(json_encode([
                'result' => true,
                'html' => $this->renderPartial('view', compact('notice'))
            ]));

        } else {
            // удалим и будем показывать все заново
            $session->destroy();
        }
    }


    public function actionAdd() {

        return $this->render('form', [
            'create' => true,
            'category' => $this->getCategory()
        ]);
    }

    public function actionEdit() {

        if(empty(Yii::$app->request->get()['id'])) {
            return $this->redirect('/admin');
        }

        $notice = Notice::findOne(Yii::$app->request->get()['id']);
        if(empty($notice->id)) {
            return $this->redirect(Url::to(['notice/add']));
        }

        return $this->render('form', [
            'create' => false,
            'notice' => $notice,
            'category' => $this->getCategory()
        ]);
    }

    public function actionPost() {

        if(Yii::$app->user->getId() <> 100) {
            throw new \Exception('У вас нет доступа к этой странице');
        }

        if(Yii::$app->request->post()) {
            $post = Yii::$app->request->post();

            if(empty(trim($post['title']) || empty($post['text']))) {
                throw new \Exception('Пустое поле');
            }

            $transaction = Yii::$app->db->beginTransaction();
            try {
                $notice = !empty($post['id']) ? Notice::findOne($post['id']) : new Notice();

                // если категория по умолчанию не прописана
                $catid = !empty($post['catid']) ?? 1;

                $notice->title = mb_substr($post['title'], 0, 240);
                $notice->text  = $post['text'];
                $notice->catid = $catid;
                $notice->save();

                $transaction->commit();
                return $this->redirect( Url::to( !empty($post['id']) ? ['notice/edit', 'id' => $post['id']] : '/admin/' ));

            } catch(\Exception $e) {
                $transaction->rollBack();
                throw $e;
            } catch(\Throwable $e) {
                $transaction->rollBack();
                throw $e;
            }
        }
        return $this->goHome();
    }

    public function actionDelete() {

        if(Yii::$app->user->getId() <> 100) {
            throw new \Exception('У вас нет доступа к этой странице');
        }

        if(!empty(Yii::$app->request->get()['id'])) {
            $notice = Notice::findOne(Yii::$app->request->get()['id']);
            if(!empty($notice)) {
                $notice->delete();
            }
        }
        return $this->redirect('/admin');
    }

    public function getCategory() {
        $category = [];
        foreach (Yii::$app->db->createCommand('select * from category')->queryAll() as $rows) {
            $category[$rows['id']] = $rows['name'];
        }
        return $category;
    }
}

views/notice/form.php
<style>
    * {box-sizing: border-box}

    .container { padding: 16px; }

    input[type=text], input[type=password],  textarea, select {
        width: 100%;
        padding: 15px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
    }

    .appendNotice {
        background-color: blue;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 10%;
        opacity: 0.9;
    }

    .appendNotice:hover { opacity:1; }
</style>
<div>
    <form action="/notice/post" method="post">
        <div class="container">
            <h1><?= $create ? 'Добавление нового уведомления' : 'Обновить уведомление' ?></h1>
            <p>Заполните все поля</p>
            <hr>
            <label for="email"><b>Заголовок (не более 240 символов)</b></label>
            <?= yii\helpers\BaseHtml::input('text', 'title', $create ? '' : $notice->title, ['placeholder' => 'Заголовок', 'required' => true]) ?>

            <label for="text"><b>Основной текст</b></label>
            <textarea placeholder="напишите основной текст уведомления" name="text" required><?= $create ? '' : $notice->text ?></textarea>
            <label for="category"><b>Укажите категорию</b></label>
            <?= yii\helpers\BaseHtml::DropDownList('catid', $create ? '' : $notice->catid, $category, ['prompt'=>'- Выберите категорию']) ?>
            <hr>
            <button type="submit" class="appendNotice"><?= $create ? 'Добавить' : 'Обновить' ?></button>

            <?php if (!$create): ?>
                <?= yii\helpers\Html::a('Удалить это сообщение', ['/notice/delete', 'id' => $notice->id], ['style' => 'float: right']) ?>
                <?= yii\helpers\BaseHtml::input('hidden', 'id', $notice->id) ?>
            <?php endif ?>
            <hr>
            <?= yii\helpers\Html::a('Все уведомления', ['/admin']) ?>
        </div>
    </form>
</div>

views/notice/view.php
<div class="n-block">
    <div class="header">
        <span><?= $notice->title ?></span>
        <a href="javascript:void(0)">
            <span class="close"></span>
        </a>
    </div>
    <div class="content">
        <?= $notice->text ?>
    </div>
    <div class="control">
        <span>Просмотров (<?= $notice->countviews ?>)</span>
    </div>
</div>